# Generated by Django 5.2.3 on 2025-07-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctanswer',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
