# Generated by Django 5.2.3 on 2025-07-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0002_alter_correctanswer_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctanswer',
            name='combination_uid',
            field=models.CharField(default=-1, max_length=36),
            preserve_default=False,
        ),
    ]
