# Generated by Django 5.2.3 on 2025-07-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0003_correctanswer_combination_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctanswercombination',
            name='category',
            field=models.CharField(blank=True, choices=[('BB', 'BB'), ('BA', 'BA')], max_length=50, null=True),
        ),
    ]
