# Generated by Django 5.2.3 on 2025-07-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0004_correctanswercombination_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctanswer',
            name='combination_uid',
        ),
        migrations.AddField(
            model_name='correctanswercombination',
            name='combination_uid',
            field=models.CharField(default=-1, max_length=36),
            preserve_default=False,
        ),
    ]
