# Generated by Django 5.2.3 on 2025-07-16 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0005_remove_correctanswer_combination_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='examadmin.branch'),
        ),
    ]
