# Generated by Django 5.2.3 on 2025-07-16 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0006_importlog_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='import_type',
            field=models.CharField(choices=[('results', 'Results Import'), ('correct_answers', 'Correct Answers Import'), ('answer_cards', 'Answer Cards Import')], default='results', max_length=20),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='imported_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
