# Generated by Django 5.2.3 on 2025-07-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0007_alter_importlog_import_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectresult',
            name='subject_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
