# Generated by Django 5.1.7 on 2025-08-04 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0008_subjectresult_subject_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='exam',
            name='groups',
        ),
        migrations.AlterUniqueTogether(
            name='sectiondetail',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='correctanswercombination',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examadmin.group'),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examadmin.group'),
        ),
        migrations.AddField(
            model_name='sectiondetail',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examadmin.group'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examadmin.group'),
        ),
        migrations.AlterUniqueTogether(
            name='sectiondetail',
            unique_together={('exam', 'section', 'group')},
        ),
        migrations.AddField(
            model_name='exam',
            name='groups',
            field=models.ManyToManyField(related_name='exams', to='examadmin.group'),
        ),
    ]
