# Generated by Django 5.2.3 on 2025-08-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0009_group_remove_exam_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiondetail',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
