# Generated by Django 5.2.3 on 2025-08-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0010_sectiondetail_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
