# Generated by Django 5.2.3 on 2025-08-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0011_alter_exam_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['id'], 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['id'], 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='studentresult',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
