# Generated by Django 5.2.3 on 2025-08-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0012_alter_branch_options_alter_class_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='pdfToken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
