# Generated by Django 5.2.3 on 2025-08-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0013_studentresult_pdftoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_foreign_language',
            field=models.BooleanField(default=False, help_text='Bu fənn xarici dil fənnidir'),
        ),
    ]
