# Generated by Django 5.2.3 on 2025-09-02 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0014_subject_is_foreign_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examadmin.class'),
        ),
    ]
