# Generated by Django 5.2.3 on 2025-09-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0015_studentresult_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'is_foreign_language')},
        ),
    ]
