# Generated by Django 5.2.3 on 2025-09-04 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0016_alter_subject_name_alter_subject_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotUploadedStudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('work_number', models.CharField(max_length=50)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_uploaded_results', to='examadmin.exam')),
            ],
        ),
    ]
