# Generated by Django 5.2.3 on 2025-09-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0017_notuploadedstudentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctanswer',
            name='question_type',
            field=models.CharField(blank=True, choices=[('close', 'Qapalı'), ('open_coded', 'Kodlaşdırıla bilən açıq tipli'), ('open', 'İzahlı açıq tipli'), ('true_false', 'Doğru/Yanlış'), ('essay', 'Esse'), ('matching', 'Uyğunlaşdırma')], max_length=50, null=True),
        ),
    ]
