# Generated by Django 5.2.3 on 2025-09-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0018_correctanswer_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
