# Generated by Django 5.2.3 on 2025-09-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0019_alter_studentresult_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='original_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
