# Generated by Django 5.2.3 on 2025-09-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0020_studentresult_original_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctanswer',
            name='penalty_score',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=7),
        ),
    ]
