# Generated by Django 5.2.3 on 2025-09-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0021_alter_correctanswer_penalty_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='additional_datas',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
