# Generated by Django 5.2.3 on 2025-09-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0022_studentresult_additional_datas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentresult',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='correctanswer',
            unique_together=set(),
        ),
    ]
