# Generated by Django 5.2.3 on 2025-09-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0023_alter_studentresult_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correctanswer',
            options={},
        ),
    ]
