# Generated by Django 5.2.3 on 2025-09-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0024_alter_correctanswer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
