# Generated by Django 5.2.3 on 2025-10-02 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0025_alter_studentresult_contact_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correctanswer',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='correctanswer',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examadmin.subject'),
        ),
    ]
