# Generated by Django 5.2.3 on 2025-11-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0026_alter_correctanswer_options_correctanswer_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctanswer',
            name='penalty_score',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='correctanswer',
            name='score',
            field=models.DecimalField(decimal_places=10, default=1.0, max_digits=20),
        ),
    ]
