# Generated by Django 5.2.3 on 2025-11-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0027_alter_correctanswer_penalty_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='type',
            field=models.CharField(choices=[('9-cu sinif buraxılış', '9-cu sinif buraxılış'), ('11-ci sinif buraxılış', '11-ci sinif buraxılış'), ('Blok imtahanı', 'Blok imtahanı'), ('Magistratura', 'Magistratura'), ('Bilik yarışı', 'Bilik yarışı'), ('Təkmilləşdirmə', 'Təkmilləşdirmə'), ('Müəllimlərin İşə Qəbulu', 'Müəllimlərin İşə Qəbulu'), ('Sertifikasiya', 'Sertifikasiya'), ('Dövlət Qulluğu', 'Dövlət Qulluğu'), ('Azərbaycan dili (dövlət dili kimi)', 'Azərbaycan dili (dövlət dili kimi)')], max_length=50),
        ),
    ]
