# Generated by Django 5.2.3 on 2025-12-03 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0028_alter_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examadmin.section'),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='variant',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
