# Generated by Django 5.2.3 on 2025-12-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0029_alter_studentresult_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='school_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
