# Generated by Django 4.2.29 on 2026-03-13 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0033_alter_exam_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='correctanswercombination',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='correctanswercombination',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examadmin.specialization'),
        ),
        migrations.AddField(
            model_name='exam',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='exams', to='examadmin.specialization'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examadmin.specialization'),
        ),
        migrations.AlterUniqueTogether(
            name='correctanswercombination',
            unique_together={('exam', 'section', 'variant', 'class_level', 'group_name', 'specialization')},
        ),
    ]
