# Generated by Django 4.2.29 on 2026-03-13 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examadmin', '0034_specialization_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sectiondetail',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sectiondetail',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examadmin.specialization'),
        ),
        migrations.AlterUniqueTogether(
            name='sectiondetail',
            unique_together={('exam', 'section', 'group', 'specialization')},
        ),
    ]
